### ISSUE TITLE
Missing parentheses in call to 'print'. Did you mean print(int '[+] Sent spoofed packet for %s' % pkt[DNSQR].qname[:-1])?

### ISSUE THREAD

**Issue by GNUGradyn** [DanMcInerney/dnsspoof#5]
Running the script returns this
```
  File "dnsspoof.py", line 59
    print '[+] Sent spoofed packet for %s' % pkt[DNSQR].qname[:-1]
                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int '[+] Sent spoofed packet for %s' % pkt[DNSQR].qname[:-1])?

```
I'm running arch linux

**Comment by GNUGradyn** [comment]
Correction: Must be run with python2, and there are many missing dependencies that I had to go track down myself, a requirements.txt would be nice

Also, nfqueue when installed from pip should be imported as "netfilterqueue", i did this by changing line 4 from `import nfqueue` to  `import netfilterqueue as nfqueue`

**Comment by T3ck1n54n3** [comment]
I got this error

localhost% python dnsspoof.py -r host.txt
  File "dnsspoof.py", line 59
    print '[+] Sent spoofed packet for %s' % pkt[DNSQR].qname[:-1]
                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[+] Sent spoofed packet for %s' % pkt[DNSQR].qname[:-1])?
localhost% python2 dnsspoof.py -r host.txt
Traceback (most recent call last):
  File "dnsspoof.py", line 1, in <module>
    from twisted.internet import reactor
ImportError: No module named twisted.internet
localhost%
